config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :courses do
    collection do
      get 'classrooms' , to: 'courses#classrooms' , as: :classrooms
    end
  end
  resources :students do
    member do
      get 'assign', to: 'students#assign_course', as: :assign_course
      get 'assign/:id_course' ,to: 'students#confirm_assign', as: :confirm_assign
    end
  end

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates :course_id ,:student_id , presence: true

  belongs_to :student
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name , :description , presence: true

  has_many :classrooms
  has_many :students, through: :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name , :register_number , presence: true

  has_many :classrooms
  has_many :courses, through: :classrooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def index
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to course_path(@course), notice: 'Course was successfully created.'
    else
      render :new
    end
  end

  def classrooms
    @courses = Course.all
  end

  def update
    if @course.update(course_params)
      redirect_to course_path(@course), notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy

    redirect_to courses_path, notice: 'Course was successfully destroyed.'
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy,:assign_course,:confirm_assign]
  before_action :set_courses , only: [:assign_course]


  def index
    @students = Student.all
  end


  def show
  end

  def new
    @student = Student.new
  end

  def assign_course
  end

  def confirm_assign
    course = Course.find(params[:id_course])
    course.classrooms.create(student: @student)

    redirect_to students_path
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to student_path(@student), notice: 'Student was successfully created.'
    else
      render :new
    end
  end


  def update
    if @student.update(student_params)
      redirect_to student_path(@student), notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @student.destroy

    redirect_to students_path, notice: 'Student was successfully destroyed.'
  end

  private

    def set_courses
      @courses = Course.all
    end

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/application/index.html.erb
<h1>O Desafio</h1>
<p>O desafio era matricular um aluno em uma determinada matéria , gerando um processo de matrícula deste aluno.</p>

<h2>Lógica de negócio</h2>
<ul>
  <li>A uma entidade chamada <strong>Student</strong>, que possui apenas <strong>name</strong> e <strong>register_number</strong></li>
  <li>A uma entidade chamada <strong>House</strong>, com <strong>name</strong> e <strong>description</strong></li>
  <li>A uma entidade chamada <strong>ClassRoom</strong>, com <strong>student_id</strong>(relacionamento com Student) e <strong>course_id</strong>(relacionamento com Course)</li>
</ul>
<p>Após cadastro das duas primeiras entidades citadas haverá possibilidade de associar um aluno a um curso , dessa forma surgi a terceira entidade que é responsável por registrar essa associação.</p>
<h2>Testes</h2>
<p>Este app foi construído usando RSpec para testes. Tentei cobrir o máximo possível sobre o código.</p>

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%=simple_form_for(@course, html: { class: "form-horizontal" }) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%=f.input :name%>
        <%=f.input :description%>
      </div>
      <div class="form-actions">
        <%=f.submit class: "btn btn-primary"%>
        <%=link_to t('buttons.back'), courses_path, class: "btn btn-default"%>
      </div>
    <%end%>
  </div>
</div>

app/views/courses/_list.html.erb
<table class="table table-striped">
  <tr>
    <th><%=t('course.name')%></th>
    <th><%=t('course.description')%></th>
    <th></th>
  </tr>
  <%@courses.each do |course|%>
    <tr>
      <td><%=link_to course.name, course_path(course)%></td>
      <td><%=course.description%></td>
      <td>
        <%=link_to "", edit_course_path(course), class: "glyphicon glyphicon-edit"%>
        <%=link_to "", course_path(course), method: :delete, class: "glyphicon glyphicon-trash", data: { confirm: t('alert.confirm') }%>
      </td>
    </tr>
  <%end%>
</table>

app/views/courses/classrooms.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
          <% @courses.each do |course| %>
            <div class="col-md-4">
              <table class="table table-bordered table-striped">
                <thead>
                  <th colspan="2"><%= course.name%></th>
                </thead>
                <tbody>
                  <% course.students.each do |student|%>
                    <tr>
                      <td><%= student.name %></td>
                      <td><%= student.register_number %></td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          <%end%>
        </div>
    </div>
</div>

app/views/courses/edit.html.erb
<h1><%=t('edit.edit_course')%></h1>

<%= render 'form' %>

app/views/courses/index.html.erb
<h1><%= t('titles.course_title') %></h1>

<%= render 'list' %>

<%= link_to t('buttons.new_course'), new_course_path , class: 'btn btn-primary'%>

app/views/courses/new.html.erb
<h1><%= t('new.new_course') %></h1>

<%= render 'form' %>

app/views/courses/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <h1><%= t('show.course') %></h1>
            <table class="table table-striped">
                <tr>
                    <th><%= t('course.name') %></th>
                    <td>
                        <%=@course.name%>
                    </td>
                </tr>
                <tr>
                    <th><%= t('course.description') %></th>
                    <td>
                        <%=@course.description%>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Desafio IS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to t('nav.challange'), root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to t('nav.home'), root_path%></li>
            <li><%= link_to t('nav.all_students'), students_path%></a></li>
            <li><%= link_to t('nav.all_courses'), courses_path%></a></li>
            <li><%= link_to t('nav.classrooms'), classrooms_courses_path%></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <%=yield%>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/students/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%=simple_form_for(@student, html: { class: "form-horizontal" }) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%=f.input :name%>
        <%=f.input :register_number%>
      </div>
      <div class="form-actions">
        <%=f.submit class: "btn btn-primary"%>
        <%=link_to t('buttons.back'), students_path, class: "btn btn-default"%>
      </div>
    <%end%>
  </div>
</div>

app/views/students/_list.html.erb
<table class="table table-striped">
  <tr>
    <th><%= t('student.name')%></th>
    <th><%= t('student.register_number')%></th>
    <th></th>
  </tr>
  <%@students.each do |student|%>
    <tr>
      <td><%=link_to student.name, student_path(student)%></td>
      <td><%=student.register_number%></td>
      <td>
        <%=link_to "", edit_student_path(student), class: "glyphicon glyphicon-edit"%>
        <%=link_to "", student_path(student), method: :delete, class: "glyphicon glyphicon-trash", data: { confirm: t('alert.confirm') }%>
      </td>
    </tr>
  <%end%>
</table>

app/views/students/assign_course.html.erb
<h1><%= t('titles.course_title')%></h1>
<table class="table table-striped">
  <tr>
    <th><%= t('course.name') %></th>
    <th><%= t('course.description') %></th>
    <th></th>
  </tr>
  <%@courses.each do |course|%>
    <tr>
      <td><%=course.name%></td>
      <td><%=course.description%></td>
      <% if course.students.include?(@student) %>
          <td><span class="label label-warning"><%= t('spams.registred')%></span></td>
      <%else%>
          <td><%=link_to t('buttons.assign'), confirm_assign_student_path(@student , course) , class: 'btn btn-success'%></td>
      <%end%>
    </tr>
  <%end%>
</table>

app/views/students/edit.html.erb
<h1><%= t('edit.student')%></h1>

<%= render 'form' %>

app/views/students/index.html.erb
<h1><%= t('titles.student_title')%></h1>

<%= render 'list' %>

<%= link_to t('buttons.new_student'), new_student_path , class: 'btn btn-primary'%>

app/views/students/new.html.erb
<h1><%= t('new.new_student')%></h1>

<%= render 'form' %>

app/views/students/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <h1><%= t('show.student')%></h1>
            <table class="table table-striped">
                <tr>
                    <th><%= t('student.name')%></th>
                    <td>
                        <%=@student.name%>
                    </td>
                </tr>
                <tr>
                    <th><%= t('student.register_number')%></th>
                    <td>
                        <%=@student.register_number%>
                    </td>
                </tr>
                <tr>
                    <th colspan="2">
                        <%=link_to t('buttons.assign_course'), assign_course_student_path(@student.id), class: "btn btn-primary"%>
                    </th>
                </tr>
            </table>
        </div>
    </div>
</div>